// <auto-generated />
namespace QuanLyDoiBong_CodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class TaoCSDLV1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TaoCSDLV1));
        
        string IMigrationMetadata.Id
        {
            get { return "202005271019120_TaoCSDLV1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
